# Generated by Django 5.1.6 on 2025-04-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_percentage',
            field=models.IntegerField(default=0, help_text='Percentage of task completed (0-100)'),
        ),
    ]
