# Generated by Django 4.2.6 on 2025-06-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_project_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dependencies',
        ),
    ]
