# Generated by Django 4.2.6 on 2025-06-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0002_resourceavailability_timeentry'),
        ('projects', '0003_alter_project_options_project_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('resource_role', models.CharField(max_length=100)),
                ('predicted_demand_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='SkillDemandAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('analysis_date', models.DateField()),
                ('current_demand', models.IntegerField(help_text='Number of tasks requiring this skill')),
                ('available_resources', models.IntegerField(help_text='Number of resources with this skill')),
                ('demand_score', models.DecimalField(decimal_places=2, help_text='Demand/Supply ratio', max_digits=5)),
                ('predicted_future_demand', models.IntegerField(help_text='Predicted demand for next month')),
            ],
            options={
                'ordering': ['-analysis_date'],
                'unique_together': {('skill_name', 'analysis_date')},
            },
        ),
        migrations.CreateModel(
            name='ProjectCostTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget_variance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_tracking', to='projects.project')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('project', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalUtilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('utilization_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('allocated_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_utilization', to='resources.resource')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('resource', 'date')},
            },
        ),
    ]
