# Generated by Django 5.2.3 on 2025-06-17 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('projects', '0003_alter_project_options_project_budget'),
        ('resources', '0004_timeentry_is_billable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISkillRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('develop', 'Skills to Develop'), ('training', 'Training Areas'), ('obsolete', 'Skills Becoming Obsolete')], max_length=20)),
                ('skill_name', models.CharField(max_length=100)),
                ('priority_score', models.IntegerField(help_text='1-10, where 10 is highest priority')),
                ('reasoning', models.TextField()),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='0.00 to 1.00', max_digits=3)),
                ('analysis_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIForecastAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusted_demand_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adjustment_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reasoning', models.TextField()),
                ('business_context_factors', models.JSONField(default=list, help_text='List of business factors considered')),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='0.00 to 1.00', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_adjustments', to='analytics.resourcedemandforecast')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIResourceAllocationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, help_text='0.00 to 1.00', max_digits=3)),
                ('reasoning', models.TextField()),
                ('estimated_completion_time', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cost_efficiency_score', models.DecimalField(decimal_places=2, help_text='0.00 to 1.00', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('suggested_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='resources.resource')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='projects.task')),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('task', 'suggested_resource')},
            },
        ),
    ]
