# Generated by Django 4.2.6 on 2025-06-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_project_budget'),
        ('dashboard', '0002_riskcategory_interventionscenario_ai_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('success_probability', models.FloatField(default=0.0)),
                ('recommendation_data', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('related_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dynamicrisk')),
            ],
            options={
                'ordering': ['-success_probability', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='interventiontemplate',
            name='risk_category',
        ),
        migrations.DeleteModel(
            name='InterventionScenario',
        ),
        migrations.DeleteModel(
            name='InterventionTemplate',
        ),
    ]
