# Generated by Django 4.2.6 on 2025-06-07 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_project_budget'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('availability_type', models.CharField(choices=[('available', 'Available'), ('vacation', 'Vacation'), ('sick_leave', 'Sick Leave'), ('personal_leave', 'Personal Leave'), ('training', 'Training'), ('meeting', 'Meeting'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='resources.resource')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='resources.resource')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.task')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('resource', 'task', 'date')},
            },
        ),
    ]
