# Generated by Django 4.2.6 on 2025-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resourceavailability_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
