# Generated by Django 5.2.3 on 2025-06-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='is_billable',
            field=models.BooleanField(default=True, help_text='Whether this time entry is billable to the client'),
        ),
    ]
