# Generated by Django 4.2.6 on 2025-06-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_timeentry_is_billable'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='location',
            field=models.CharField(blank=True, help_text="Location (e.g., 'New York, USA', 'London, UK', 'Remote')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='timezone',
            field=models.CharField(default='UTC', help_text="Resource's timezone (e.g., 'America/New_York', 'Europe/London', 'Asia/Tokyo')", max_length=100),
        ),
    ]
